-- SCHEMA DA APLICAÇÃO
CREATE SCHEMA CAR_INSURANCE_QUOTES AUTHORIZATION SA;

-- TABELA DE VEÍCULOS
CREATE TABLE CAR_INSURANCE_QUOTES.CARS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    MODEL VARCHAR(80),
    MANUFACTURER VARCHAR(80),
    CAR_YEAR VARCHAR(4),
    FIPE_VALUE NUMERIC(15, 2) NOT NULL,
    CONSTRAINT PK_CARS PRIMARY KEY(ID)
);

-- TABELA DE MOTORISTAS
CREATE TABLE CAR_INSURANCE_QUOTES.DRIVERS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    DOCUMENT VARCHAR(11),
    BIRTHDATE DATE NOT NULL,
    CONSTRAINT PK_DRIVERS PRIMARY KEY(ID)
);

-- TABELA DE CLIENTES
CREATE TABLE CAR_INSURANCE_QUOTES.CUSTOMERS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(80),
    DRIVER_ID BIGINT NOT NULL,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY(ID),
    CONSTRAINT FK_CUSTOMERS_WITH_DRIVERS FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(ID)
);
CREATE INDEX IDX_CUSTOMERS_DRIVER_ID ON CAR_INSURANCE_QUOTES.CUSTOMERS(DRIVER_ID);

-- TABELA DE MOTORISTAS DOS VEÍCULOS
CREATE TABLE CAR_INSURANCE_QUOTES.CAR_DRIVERS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CAR_ID BIGINT NOT NULL,
    DRIVER_ID BIGINT NOT NULL,
    MAIN_DRIVER BOOLEAN NOT NULL,
    CONSTRAINT PK_CAR_DRIVERS PRIMARY KEY(ID),
    CONSTRAINT FK_CAR_DRIVERS_WITH_CARS FOREIGN KEY (CAR_ID) REFERENCES CARS(ID),
    CONSTRAINT FK_CAR_DRIVERS_WITH_DRIVERS FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(ID),
    CONSTRAINT UK_CAR_DRIVERS_MAIN_DRIVER_AND_CAR_ID UNIQUE (MAIN_DRIVER, CAR_ID)
);
CREATE INDEX IDX_CAR_DRIVERS_CAR_ID ON CAR_INSURANCE_QUOTES.CAR_DRIVERS(CAR_ID);
CREATE INDEX IDX_CAR_DRIVERS_DRIVER_ID ON CAR_INSURANCE_QUOTES.CAR_DRIVERS(DRIVER_ID);

-- TABELA DE SINISTROS
CREATE TABLE CAR_INSURANCE_QUOTES.CLAIMS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CAR_ID BIGINT,
    DRIVER_ID BIGINT,
    EVENT_DATE DATE,
    CONSTRAINT PK_CLAIMS PRIMARY KEY(ID),
    CONSTRAINT FK_CLAIMS_WITH_CARS FOREIGN KEY (CAR_ID) REFERENCES CARS(ID),
    CONSTRAINT FK_CLAIMS_WITH_DRIVERS FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(ID)
);
CREATE INDEX IDX_CLAIMS_CAR_ID ON CAR_INSURANCE_QUOTES.CLAIMS(CAR_ID);
CREATE INDEX IDX_CLAIMS_DRIVER_ID ON CAR_INSURANCE_QUOTES.CLAIMS(DRIVER_ID);


-- TABELA DE SEGUROS
CREATE TABLE CAR_INSURANCE_QUOTES.INSURANCES (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID BIGINT NOT NULL,
    CREATION_DT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CAR_ID BIGINT NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    FIPE_PERCENTAGE NUMERIC(4, 2) NOT NULL,
    AMOUNT NUMERIC(15, 2) NOT NULL,
    CONSTRAINT PK_INSURANCE PRIMARY KEY(ID),
    CONSTRAINT FK_INSURANCES_WITH_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT FK_INSURANCES_WITH_CARS FOREIGN KEY (CAR_ID) REFERENCES CARS(ID)
);
CREATE INDEX IDX_INSURANCES_CUSTOMER_ID ON CAR_INSURANCE_QUOTES.INSURANCES(CUSTOMER_ID);
CREATE INDEX IDX_INSURANCES_CAR_ID ON CAR_INSURANCE_QUOTES.INSURANCES(CAR_ID);

-- REGISTROS DE VEÍCULOS
INSERT INTO CAR_INSURANCE_QUOTES.CARS (MODEL, MANUFACTURER, CAR_YEAR, FIPE_VALUE) VALUES('Strada Opening Edition 1.3 Flex 8V Cd', 'Fiat', '2003', 22780);
INSERT INTO CAR_INSURANCE_QUOTES.CARS (MODEL, MANUFACTURER, CAR_YEAR, FIPE_VALUE) VALUES('116Ia 1.6 Tb 16V 136Cv 5P', 'BMW', '2012', 70670);
INSERT INTO CAR_INSURANCE_QUOTES.CARS (MODEL, MANUFACTURER, CAR_YEAR, FIPE_VALUE) VALUES('Gallardo Coupe Lp560 4', 'Lamborghini', '2009' , 936959);

-- REGISTROS DE MOTORISTAS
INSERT INTO CAR_INSURANCE_QUOTES.DRIVERS (DOCUMENT, BIRTHDATE) VALUES('38545528201', '2000-05-20');
INSERT INTO CAR_INSURANCE_QUOTES.DRIVERS (DOCUMENT, BIRTHDATE) VALUES('93461350030', '2000-05-20');
INSERT INTO CAR_INSURANCE_QUOTES.DRIVERS (DOCUMENT, BIRTHDATE) VALUES('56254205762', '1990-05-20');

-- REGISTROS DE CLIENTES
INSERT INTO CAR_INSURANCE_QUOTES.CUSTOMERS (NAME, DRIVER_ID) VALUES('Renata Maldonado', 1);
INSERT INTO CAR_INSURANCE_QUOTES.CUSTOMERS (NAME, DRIVER_ID) VALUES('Eduarda Bosco', 2);
INSERT INTO CAR_INSURANCE_QUOTES.CUSTOMERS (NAME, DRIVER_ID) VALUES('Vanda Saraiva', 3);

-- REGISTROS DE MOTORISTAS DOS VEÍCULOS
INSERT INTO CAR_INSURANCE_QUOTES.CAR_DRIVERS (CAR_ID, DRIVER_ID, MAIN_DRIVER) VALUES(1, 1, TRUE);
INSERT INTO CAR_INSURANCE_QUOTES.CAR_DRIVERS (CAR_ID, DRIVER_ID, MAIN_DRIVER) VALUES(2, 2, TRUE);
INSERT INTO CAR_INSURANCE_QUOTES.CAR_DRIVERS (CAR_ID, DRIVER_ID, MAIN_DRIVER) VALUES(3, 3, TRUE);

-- REGISTROS DE SINISTROS
INSERT INTO CAR_INSURANCE_QUOTES.CLAIMS (CAR_ID, DRIVER_ID, EVENT_DATE) VALUES(NULL, 1, '2023-05-20');
INSERT INTO CAR_INSURANCE_QUOTES.CLAIMS (CAR_ID, DRIVER_ID, EVENT_DATE) VALUES(NULL, 2, '2023-05-20');
INSERT INTO CAR_INSURANCE_QUOTES.CLAIMS (CAR_ID, DRIVER_ID, EVENT_DATE) VALUES(2, NULL, '2023-05-20');


