CREATE SCHEMA CAR_INSURANCE_QUOTES AUTHORIZATION SA;

-- TABELA DE CLIENTES
CREATE TABLE CAR_INSURANCE_QUOTES.CUSTOMERS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(80),
    DRIVER_ID BIGINT,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY(ID)
);

-- TABELA DE MOTORISTAS
CREATE TABLE CAR_INSURANCE_QUOTES.DRIVERS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    DOCUMENT VARCHAR(11),
    BIRTHDATE DATE,
    CONSTRAINT PK_DRIVERS PRIMARY KEY(ID)
);

-- TABELA DE VEÍCULOS
CREATE TABLE CAR_INSURANCE_QUOTES.CARS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    MODEL VARCHAR(20),
    MANUFACTURER VARCHAR(80),
   "YEAR" SMALLINT,
    FIPE_VALUE NUMERIC(15, 2),
    CONSTRAINT PK_CARS PRIMARY KEY(ID)
);

-- TABELA DE MOTORISTAS DOS VEÍCULOS
CREATE TABLE CAR_INSURANCE_QUOTES.CAR_DRIVERS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CAR_ID BIGINT,
    DRIVER_ID BIGINT,
    IS_MAIN_DRIVER BOOLEAN,
    CONSTRAINT PK_CAR_DRIVERS PRIMARY KEY(ID),
    CONSTRAINT FK_CAR_DRIVERS_WITH_CARS FOREIGN KEY (CAR_ID) REFERENCES CARS(ID),
    CONSTRAINT FK_CAR_DRIVERS_WITH_DRIVERS FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(ID)
);

-- TABELA DE SINISTROS
CREATE TABLE CAR_INSURANCE_QUOTES.CLAIMS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CAR_ID BIGINT,
    DRIVER_ID BIGINT,
    EVENT_DATE DATE,
    CONSTRAINT PK_CLAIMS PRIMARY KEY(ID),
    CONSTRAINT FK_CLAIMS_WITH_CARS FOREIGN KEY (CAR_ID) REFERENCES CARS(ID),
    CONSTRAINT FK_CLAIMS_WITH_DRIVERS FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(ID)
);
CREATE INDEX IDX_CLAIMS_CAR_ID ON CAR_INSURANCE_QUOTES.CLAIMS(CAR_ID);
CREATE INDEX IDX_CLAIMS_DRIVER_ID ON CAR_INSURANCE_QUOTES.CLAIMS(DRIVER_ID);


-- TABELA DE SEGUROS
CREATE TABLE CAR_INSURANCE_QUOTES.INSURANCES (
    ID BIGINT GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID BIGINT,
    CREATION_DT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CAR_ID BIGINT,
    IS_ACTIVE BOOLEAN,
    CALCULATED_VALUE NUMERIC(15, 2),
    CONSTRAINT PK_INSURANCE PRIMARY KEY(ID),
    CONSTRAINT FK_INSURANCES_WITH_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    CONSTRAINT FK_INSURANCES_WITH_CARS FOREIGN KEY (CAR_ID) REFERENCES CARS(ID)
);

